
#pragma once

#include "NativeGameplayTags.h"


namespace ViewModeTag
{
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace LocomotionModeTag
{
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
}

namespace RotationModeTag
{
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OrientToMovement)
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Strafe)
}

namespace StanceTag
{
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stand)
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouch)
}

namespace GaitTag
{
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walk)
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Run)
	CANCERANIMATION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint)
}
